[phases.setup]
# Install system packages needed for video processing
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "ffmpeg-full", "python311Packages.yt-dlp"]

[phases.install]
# Install Node dependencies
cmds = [
  "npm ci --production=false"
]

[phases.build]
# Build the Next.js app
cmds = [
  "npm run build"
]

[start]
# Start directly with npm start (tools are already installed)
cmd = "npm start"

[variables]
# Ensure Python uses UTF-8
PYTHONIOENCODING = "utf-8"
# Node environment
NODE_ENV = "production" 