[phases.setup]
# Install system packages
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
# Install Node dependencies
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
# Install Python packages and build
cmds = [
  "pip install --upgrade pip",
  "pip install yt-dlp",
  "yt-dlp --version",
  "ffmpeg -version",
  "npm run build"
]

[start]
# Start the application
cmd = "npm start" 