# TwipClip build configuration for Railway
# Last updated: 2025-06-05

[phases.setup]
# Install system packages
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "ffmpeg", "curl"]

[phases.install]
# Install Node dependencies
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
# Build Next.js (yt-dlp will be installed at runtime)
cmds = [
  "npm run build"
]

[start]
# Start the application using the script that installs yt-dlp
cmd = "npm run start:railway" 