[phases.setup]
# Install system packages including yt-dlp
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "yt-dlp", "ffmpeg"]

[phases.install]
# Install Node dependencies
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
# Build Next.js and verify tools
cmds = [
  "export PATH=/nix/var/nix/profiles/default/bin:$PATH",
  "which yt-dlp && yt-dlp --version || echo 'yt-dlp not found in PATH'",
  "which ffmpeg && ffmpeg -version || echo 'ffmpeg not found in PATH'",
  "npm run build"
]

[start]
# Start the application with proper PATH
cmd = "export PATH=/nix/var/nix/profiles/default/bin:$PATH && npm start" 