[phases.setup]
# Install system packages needed for video processing
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "ffmpeg-full", "gcc"]
aptPkgs = ["build-essential"]

[phases.install]
# Install dependencies
cmds = [
  "npm install --production=false"
]

[phases.build]
# Install yt-dlp and build Next.js
cmds = [
  "pip install --user yt-dlp",
  "export PATH=$HOME/.local/bin:$PATH",
  "npm run build"
]

[start]
# Start with PATH including user-installed packages
cmd = "export PATH=$HOME/.local/bin:$PATH && npm start"

[variables]
# Environment variables
PYTHONIOENCODING = "utf-8"
NODE_ENV = "production"
# Add user bin to PATH
PATH = "$PATH:$HOME/.local/bin" 