# TwipClip build configuration for Railway
# Last updated: 2025-06-05

[phases.setup]
# Install system packages
nixPkgs = ["nodejs-18_x", "python311", "ffmpeg"]

[phases.install]
# Install Node dependencies and yt-dlp
cmds = [
  "npm install --legacy-peer-deps",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install yt-dlp"
]

[phases.build]
# Build Next.js
cmds = ["npm run build"]

[start]
# Start the application
cmd = "npm start" 