[phases.setup]
# Install system packages
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "ffmpeg"]

[phases.install]
# Install Node dependencies
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
# Install yt-dlp and build Next.js
cmds = [
  "pip install --break-system-packages yt-dlp",
  "export PATH=$HOME/.local/bin:/usr/local/bin:$PATH",
  "which yt-dlp && yt-dlp --version || echo 'yt-dlp not found in PATH'",
  "which ffmpeg && ffmpeg -version || echo 'ffmpeg not found in PATH'",
  "npm run build"
]

[start]
# Start the application with proper PATH
cmd = "export PATH=$HOME/.local/bin:/usr/local/bin:$PATH && npm start" 